require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DatumTypesController do

  # This should return the minimal set of attributes required to create a valid
  # DatumType. As you add validations to DatumType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DatumTypesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all datum_types as @datum_types" do
      datum_type = DatumType.create! valid_attributes
      get :index, {}, valid_session
      assigns(:datum_types).should eq([datum_type])
    end
  end

  describe "GET show" do
    it "assigns the requested datum_type as @datum_type" do
      datum_type = DatumType.create! valid_attributes
      get :show, {:id => datum_type.to_param}, valid_session
      assigns(:datum_type).should eq(datum_type)
    end
  end

  describe "GET new" do
    it "assigns a new datum_type as @datum_type" do
      get :new, {}, valid_session
      assigns(:datum_type).should be_a_new(DatumType)
    end
  end

  describe "GET edit" do
    it "assigns the requested datum_type as @datum_type" do
      datum_type = DatumType.create! valid_attributes
      get :edit, {:id => datum_type.to_param}, valid_session
      assigns(:datum_type).should eq(datum_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DatumType" do
        expect {
          post :create, {:datum_type => valid_attributes}, valid_session
        }.to change(DatumType, :count).by(1)
      end

      it "assigns a newly created datum_type as @datum_type" do
        post :create, {:datum_type => valid_attributes}, valid_session
        assigns(:datum_type).should be_a(DatumType)
        assigns(:datum_type).should be_persisted
      end

      it "redirects to the created datum_type" do
        post :create, {:datum_type => valid_attributes}, valid_session
        response.should redirect_to(DatumType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved datum_type as @datum_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        DatumType.any_instance.stub(:save).and_return(false)
        post :create, {:datum_type => {  }}, valid_session
        assigns(:datum_type).should be_a_new(DatumType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DatumType.any_instance.stub(:save).and_return(false)
        post :create, {:datum_type => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested datum_type" do
        datum_type = DatumType.create! valid_attributes
        # Assuming there are no other datum_types in the database, this
        # specifies that the DatumType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DatumType.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => datum_type.to_param, :datum_type => { "these" => "params" }}, valid_session
      end

      it "assigns the requested datum_type as @datum_type" do
        datum_type = DatumType.create! valid_attributes
        put :update, {:id => datum_type.to_param, :datum_type => valid_attributes}, valid_session
        assigns(:datum_type).should eq(datum_type)
      end

      it "redirects to the datum_type" do
        datum_type = DatumType.create! valid_attributes
        put :update, {:id => datum_type.to_param, :datum_type => valid_attributes}, valid_session
        response.should redirect_to(datum_type)
      end
    end

    describe "with invalid params" do
      it "assigns the datum_type as @datum_type" do
        datum_type = DatumType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DatumType.any_instance.stub(:save).and_return(false)
        put :update, {:id => datum_type.to_param, :datum_type => {  }}, valid_session
        assigns(:datum_type).should eq(datum_type)
      end

      it "re-renders the 'edit' template" do
        datum_type = DatumType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DatumType.any_instance.stub(:save).and_return(false)
        put :update, {:id => datum_type.to_param, :datum_type => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested datum_type" do
      datum_type = DatumType.create! valid_attributes
      expect {
        delete :destroy, {:id => datum_type.to_param}, valid_session
      }.to change(DatumType, :count).by(-1)
    end

    it "redirects to the datum_types list" do
      datum_type = DatumType.create! valid_attributes
      delete :destroy, {:id => datum_type.to_param}, valid_session
      response.should redirect_to(datum_types_url)
    end
  end

end
